package com.michaldrabik.ui_model

data class Settings(
  val isInitialRun: Boolean,
  val episodesNotificationsEnabled: Boolean,
  val episodesNotificationsDelay: NotificationDelay,
  val watchlistShowsSortBy: SortOrder,
  val archiveShowsSortBy: SortOrder,
  val myShowsWatchingSortBy: SortOrder,
  val myShowsUpcomingSortBy: SortOrder,
  val myShowsFinishedSortBy: SortOrder,
  val myShowsAllSortBy: SortOrder,
  val myShowsRunningIsCollapsed: Boolean,
  val myShowsIncomingIsCollapsed: Boolean,
  val myShowsEndedIsCollapsed: Boolean,
  val myRecentsAmount: Int,
  val showAnticipatedShows: Boolean,
  val discoverFilterGenres: List<Genre>,
  val discoverFilterNetworks: List<Network>,
  val discoverFilterFeed: DiscoverFeed,
  val progressSortOrder: SortOrder,
  val archiveIncludeStatistics: Boolean,
  val specialSeasonsEnabled: Boolean,
  val showAnticipatedMovies: Boolean,
  val discoverMoviesFilterGenres: List<Genre>,
  val discoverMoviesFilterFeed: DiscoverFeed,
  val watchlistMoviesSortBy: SortOrder,
  val myMoviesAllSortBy: SortOrder,
  val progressMoviesSortBy: SortOrder,
  val showCollectionShows: Boolean,
  val showCollectionMovies: Boolean,
  val widgetsShowLabel: Boolean,
  val listsSortBy: SortOrder,
  val progressUpcomingEnabled: Boolean,
) {

  companion object {
    fun createInitial() =
      Settings(
        isInitialRun = true,
        episodesNotificationsEnabled = true,
        episodesNotificationsDelay = NotificationDelay.WHEN_AVAILABLE,
        watchlistShowsSortBy = SortOrder.NAME,
        archiveShowsSortBy = SortOrder.NAME,
        myShowsWatchingSortBy = SortOrder.NAME,
        myShowsUpcomingSortBy = SortOrder.NAME,
        myShowsFinishedSortBy = SortOrder.NAME,
        myShowsAllSortBy = SortOrder.NAME,
        myShowsRunningIsCollapsed = true,
        myShowsIncomingIsCollapsed = true,
        myShowsEndedIsCollapsed = true,
        myRecentsAmount = 4,
        showAnticipatedShows = true,
        discoverFilterGenres = emptyList(),
        discoverFilterNetworks = emptyList(),
        discoverFilterFeed = DiscoverFeed.TRENDING,
        progressSortOrder = SortOrder.NAME,
        archiveIncludeStatistics = true,
        specialSeasonsEnabled = false,
        showAnticipatedMovies = true,
        discoverMoviesFilterGenres = emptyList(),
        discoverMoviesFilterFeed = DiscoverFeed.TRENDING,
        watchlistMoviesSortBy = SortOrder.NAME,
        myMoviesAllSortBy = SortOrder.NAME,
        progressMoviesSortBy = SortOrder.NAME,
        showCollectionShows = true,
        showCollectionMovies = true,
        widgetsShowLabel = true,
        listsSortBy = SortOrder.NEWEST,
        progressUpcomingEnabled = true,
      )
  }
}
